### ISSUE TITLE
Any plans to update Android to version 5

### ISSUE THREAD

**Issue by FranciZ** [NativeScript/nativescript-facebook#201]
App install ads require apps to implement version 5 of the plugin. Are there any plans to upgrade the android side of the plugin to 5?

As far as I see iOS is already on version5.

Thanks!

**Comment by DimitarTodorov** [comment]
Hi @FranciZ ,
We've migrated to latest version of iOS android.facebook.sdk since there was an issue, which was fixed in the latest sdk. There was no need at the time being to udpate the android.sdk of the plugin to latest. We will review the changelog of the sdk and will update it at some point. 
Meanwhile we love contributors and we are open for PRs. You are welcome to update it and propose a PR with the change, we can review and release an update of the plugin after. 
Regards,
NativeScript Team

**Comment by narusevic** [comment]
After updating to newest tns, angular versions, this error appeared: https://stackoverflow.com/questions/57543127/android-gradle-fail-aapt-error-resource-color-com-facebook-button-background

**Comment by narusevic** [comment]
Created PR https://github.com/NativeScript/nativescript-facebook/pull/208

**Comment by zbranzov** [comment]
Published in nativescript-facebook@4.2.0
