### ISSUE TITLE
Can't start demo

### ISSUE THREAD

**Issue by jorotenev** [NativeScript/nativescript-facebook#57]
Hi there.  
Using a freshly created Nexus emulator,
```
$ uname -a
Linux georgi-laptop 4.10.0-30-generic #34~16.04.1-Ubuntu SMP Wed Aug 2 02:13:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
$ git clone git@github.com:NativeScript/nativescript-facebook.git && cd nativescript-facebook
$ tns run android
...
```
Output of the `tns run android` is [here](https://pastebin.com/veWURPPn) (says build was successful, but there were warnings about assets on the last lines)
When the app launches, I get this:
![screenshot from 2017-08-10 21-55-45](https://user-images.githubusercontent.com/8976783/29189459-e45596c0-7e16-11e7-8fd7-d9428ee927bc.png)

I'm new to NS, but I've been able to run other sample apps successfully(e.g. the Groceries demo from the official docs).
What am I doing wrong? 

Cheers :)

**Comment by angeltsvetkov** [comment]
Hi @jorotenev. Welcome to the NativeScript community. It is great pleasure to me that you are experimenting with nativescript-facebook. I suspect that the problem you faced with is due to the fact that you didn't transpile the plugin's *.ts files. NativeScript plugins are JavaScript files. If you do not run tsc in src folder - there are no JavaScript files generated. So give it a try. Delete your node_modiles folder (in the demo app), then transpile the plugin's files (cd src && tsc), then tns run android. I hope this will solve the problem (delete the platforms folder as well, just in case). Please let me know if you have any additional issues.

Наздраве!

**Comment by jorotenev** [comment]
Ah of course. I think couple of days ago I opened the repo in webstorm which transpiles files automatically so I could run it. I had problems with fb then so started from scratch just from the terminal so never got the .js files.

Thanks for the prompt reply :)
