### ISSUE TITLE
Facebook Sharing

### ISSUE THREAD

**Issue by Sharique-Hasan** [NativeScript/nativescript-facebook#73]
Question:

When can we expect the facebook sharing support in the plugin?

**Comment by NickIliev** [comment]
@Sharique-Hasan the plugin is open source and everyone can contribute and implement features that improve or provides enhanced functionality.

Meanwhile, you can use[ this plugin for social share](https://github.com/tjvantoll/nativescript-social-share)

**Comment by rAnAaRsl** [comment]
do we have an option to implement Facebook App invite Dialogue ?

**Comment by jannotabamo** [comment]
Since facebook removed `publish_actions` in the latest version of graph api, I can't now use `me/feed?message=your.message` endpoint of graph API, instead facebook introduces Facebook Sharing. heres the link: https://developers.facebook.com/docs/sharing/ but It didn't provide an Graph Api endpoint for it. Is there any way to enable sharing? i badly need it on my app.

**Comment by zbranzov** [comment]
The feature is released in nativescript-facebook@2.3.0
