### ISSUE TITLE
Logout on iOS

### ISSUE THREAD

**Issue by b-hobbs** [NativeScript/nativescript-facebook#82]
I'm trying to implement logout but in iOS it does not seem to work as expected. After logging out I'd expect the next login to require an email and password to be entered but it remembers the last account and just asks to continue, making it impossible to use another facebook account. On android it does request another email and password. Any help would be appreciated. 

### Which platform(s) does your issue occur on?
iOS

### Please, provide the following version numbers that your issue occurs with:

- CLI: 3.4.0
- Cross-platform modules: 3.4.0
- Runtime(s): 3.4.0
- Plugin(s): 2.1.0

### Please, tell us how to recreate the issue in as much detail as possible. 
I can't get the demo working but I basically followed the custom way of the demo.

Facebook.login((error, data) => {});
Facebook.logout(() => console.log("loggout facebook"));

**Comment by vmachuca** [comment]
same problem here!

**Comment by zbranzov** [comment]
@vmachuca @b-hobbs You can change the login behavior in the 'init' function by using the second optional parameter 'LoginBehavior.LoginBehaviorWeb'. This way everytime a user is logged out it will be prompted to input credentials on login. Notice that this applies only when custom button is used.

**Comment by zbranzov** [comment]
I'm closing this. Please write back if there is anything unclear.

**Comment by lin-brian-l** [comment]
@zbranzov Can you give a more explicit explanation about how to use "LoginBehavior.LoginBehaviorWeb"? I've tried implementing variations on the following code, but it either throws an error or has no effect.

`let nsFacebook = require('nativescript-facebook');
import * as application from 'application';

application.on(application.launchEvent, function(args) {
    nsFacebook.init("fb_id", LoginBehavior.LoginBehaviorWeb);
});`

**Comment by lin-brian-l** [comment]
@zbranzov thanks for the reply. I've been able to use a custom login function and log out of Facebook. To clarify, users can properly sign in/out of Facebook properly on both Android and iOS, but I have an issue on Android where, after signing in via Facebook once, the phone will always remember that user's information and automatically perform the login process instead of re-prompting the user for their credentials. It isn't a huge issue, but it is inconvenient because it prevents users from logging in to a different account via Facebook. I replicated this issue in the demo app (I only changed the Facebook app ID in `app.module.ts`) as well; have you seen issue before? If so, do you have any ideas of how to solve it?
