### ISSUE TITLE
setAutoLogAppEventsEnabled

### ISSUE THREAD

**Issue by mikloshumli** [NativeScript/nativescript-facebook#88]
Hi,
I have a problem when I implement this plugin:
TypeError: Cannot read property 'setAutoLogAppEventsEnabled' of undefined
Can you help me?

**Comment by Nicholas1490** [comment]
Hi,

I am getting the same error on android: 
TypeError: Cannot read property 'setAutoLogAppEventsEnabled' of undefined
This happens when the app launches. No actions were done before the error (Clicking login)

IOS works fine.

- Platform: Android
- OS version: 8.0, 6.0
- Device Model: One Plus 5T / One Plus One

│ Component        │ Current version │ Latest version │ Information │
│ nativescript     │ 3.4.3           │ 3.4.3          │ Up to date  │
│ tns-core-modules │ 3.4.1           │ 3.4.1          │ Up to date  │
│ tns-android      │ 3.4.2           │ 3.4.2          │ Up to date  │
│ tns-ios          │ 3.4.1           │ 3.4.1          │ Up to date  │

**Error**

`An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.kanchange.tt/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'setAutoLogAppEventsEnabled' of undefined
File: "file:///data/data/com.kanchange.tt/files/app/tns_modules/nativescript-facebook/login-manager.js, line: 15, column: 28

StackTrace: 
	Frame: function:'init', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/nativescript-facebook/login-manager.js', line: 15, column: 29
	Frame: function:'', file:'file:///data/data/com.kanchange.tt/files/app/app.js', line: 16, column: 29
	Frame: function:'Observable.notify', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
	Frame: function:'ActivityCallbacksImplementation.notifyLaunch', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 621, column: 21
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 585, column: 29
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6809)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: com.tns.NativeScriptException: 
Calling js method onCreate failed

TypeError: Cannot read property 'setAutoLogAppEventsEnabled' of undefined
File: "file:///data/data/com.kanchange.tt/files/app/tns_modules/nativescript-facebook/login-manager.js, line: 15, column: 28

StackTrace: 
	Frame: function:'init', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/nativescript-facebook/login-manager.js', line: 15, column: 29
	Frame: function:'', file:'file:///data/data/com.kanchange.tt/files/app/app.js', line: 16, column: 29
	Frame: function:'Observable.notify', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/data/observable/observable.js', line: 103, column: 23
	Frame: function:'ActivityCallbacksImplementation.notifyLaunch', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 621, column: 21
	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/frame.js', line: 585, column: 29
	Frame: function:'NativeScriptActivity.onCreate', file:'file:///data/data/com.kanchange.tt/files/app/tns_modules/tns-core-modules/ui/frame/activity.js', line: 20, column: 25


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
	at android.app.Activity.performCreate(Activity.java:6998)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1230)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2899)
	... 9 more`

**Comment by Nicholas1490** [comment]
It works now!
Magically.... I removed the android platform and added it back.

**Comment by DimitarTachev** [comment]
Hi guys,

This error is thrown when the Facebook Android SDK is missing in the App package. Most probably caused by some issue during app build. Removing the platform folder and making a fresh copy should fix it in most of the cases. 

Please, update us back if the clean build doesn't help or you have some steps reproducing the missing SDK state.
